### ISSUE TITLE
Implementing `map()` and `filter()`

### ISSUE THREAD

**Issue by Contentmaudlin** [Contentmaudlin/kernel_generators#1]
- It makes sense for `map()` and `filter()` to return a new generator object rather than manipulating the existing generator.
- How should `map()` and `filter()` behave when the user threads? I think we need to implement `MappedGenerator` and `FilteredGenerator` classes that should plug to the same source. 

Here is an example. What is the behavior?
```
fibGn g(1);
if (fork()) {
   addG = g.map([](int x) { return x + 1 ; } );
   for (auto &x : addG) {
      cout << x << endl;
   }
} else {
   for (auto &x : g) {
      cout << x << endl;
   }
}
```

**Comment by dave-epstein** [comment]
:)
