### ISSUE TITLE
Implementing `lookback`

### ISSUE THREAD

**Issue by Contentmaudlin** [Contentmaudlin/kernel_generators#2]
I think the following should be true:
- lookback variables can only be defined inside a generator definition -- so they are private (protected?) classes inside `Gn`.
- Assignment to lookback variables should be limited to one assignment inside the `yield()` function. The history state that is preserved is based on the value of the variables when `yield()` is returned.

I think the second one is easy to implement -- we have a main worker function that calls `yield()` and then grabs the values of the iterator variables, handles the circular buffer. 

The main issue is how to limit the amount of assignment that can be made to lookback variables to **one**. There are two ways I can think of:

1. At runtime. Have `operator=` flip a flag and throw an error when that flag is flipped twice. The worker thread resets flag when `yield()` returns.
2. We don't actually limit the number of assignments. The user assigns with the assumption that lookback stores the history of the variables as they exist at the end of the `yield()` function.

**Comment by dave-epstein** [comment]
We can close this now.
